//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToshkentGullari.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToshkentGullari.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26А, Buxoro street, Tashkent, 100029.
        /// </summary>
        public static string AddressLine {
            get {
                return ResourceManager.GetString("AddressLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical address.
        /// </summary>
        public static string AddressTitle {
            get {
                return ResourceManager.GetString("AddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads from SpeedyAd.
        /// </summary>
        public static string Ads {
            get {
                return ResourceManager.GetString("Ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string CategoriesAll {
            get {
                return ResourceManager.GetString("CategoriesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products we offer.
        /// </summary>
        public static string CategoriesTitle {
            get {
                return ResourceManager.GetString("CategoriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is easy to get in touch with Toshkent Gullari..
        /// </summary>
        public static string ContactSubtitle {
            get {
                return ResourceManager.GetString("ContactSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We would we be glad to hear from you..
        /// </summary>
        public static string ContactSubtitleSmall {
            get {
                return ResourceManager.GetString("ContactSubtitleSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Toshkent Gullari.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright and colorful rainbow colors, delicate aromas of flowers. You&apos;ve come to the fabulous world of flower - salon &quot;Flowers in Tashkent.&quot; This is not only a virtual floristic network - this is a real florist Tashkent. Salon &quot;Flowers of Tashkent&quot; was founded over 25 years ago, and is one of the first to flower shops of the capital. Since then, we try to keep our tradition of providing quality floristic services and at the same time, we are improving every year and improve their qualifications, learning new  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string FormButtonMessage {
            get {
                return ResourceManager.GetString("FormButtonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lease, leave your message or thoughts. They are more than welcome!.
        /// </summary>
        public static string FormMessage {
            get {
                return ResourceManager.GetString("FormMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string FormPhone {
            get {
                return ResourceManager.GetString("FormPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact form.
        /// </summary>
        public static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have.
        /// </summary>
        public static string FormType {
            get {
                return ResourceManager.GetString("FormType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say it:.
        /// </summary>
        public static string FormUserMessage {
            get {
                return ResourceManager.GetString("FormUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FormUserName {
            get {
                return ResourceManager.GetString("FormUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like us on Facebook.
        /// </summary>
        public static string LikeUS {
            get {
                return ResourceManager.GetString("LikeUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out.
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string LockedOutMessage {
            get {
                return ResourceManager.GetString("LockedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map location.
        /// </summary>
        public static string MapTitle {
            get {
                return ResourceManager.GetString("MapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Toshkent Gullari&apos;s collection!.
        /// </summary>
        public static string ProdectsIndexTitle {
            get {
                return ResourceManager.GetString("ProdectsIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toshkent Gullari | Biggest flower store in Tashkent.
        /// </summary>
        public static string ProductsTitle {
            get {
                return ResourceManager.GetString("ProductsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search our web sites.
        /// </summary>
        public static string SearchGoogle {
            get {
                return ResourceManager.GetString("SearchGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SortName {
            get {
                return ResourceManager.GetString("SortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string SortPrice {
            get {
                return ResourceManager.GetString("SortPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort products by:.
        /// </summary>
        public static string SortText {
            get {
                return ResourceManager.GetString("SortText", resourceCulture);
            }
        }
    }
}
